# Generated by Django 4.2.18 on 2025-01-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhr', '0013_blockentry_fast_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blockentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourceblacklistentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whitelistentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
