language: python

python:
  - 2.6
  - 2.7

services:
  - postgresql

install:
  - install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database bhr;' -U postgres

script: python manage.py test -v 2
