db:
  image: postgres
  environment:
    POSTGRES_DB: bhr

web:
  environment:
    DATABASE_URL: postgres://postgres@db/bhr
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
